[package]
name = "yntra-crypto"
version = "0.1.5"
edition = "2024"
description = "Yntra Vault - Auditable core cryptographic and memory protection engine"
license = "MIT"

[lib]
name = "yntra_crypto"
path = "src/lib.rs"

[dependencies]
argon2 = { version = "0.5", features = ["std"] }
chacha20poly1305 = "0.10"
aes-gcm = "0.10"
hkdf = "0.12"
sha2 = "0.10"
sha1 = "0.10"
blake3 = "1.5"
hmac = "0.12"
zeroize = { version = "1", features = ["derive"] }
subtle = "2.6"
rand = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
p256 = { version = "0.13", features = ["ecdsa", "pkcs8"] }
uuid = { version = "1", features = ["v4", "serde"] }
data-encoding = "2.6"
ed25519-dalek = { version = "2.1", default-features = false, features = ["std", "rand_core", "zeroize"] }

[target.'cfg(windows)'.dependencies]
windows-core = "0.58"
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_System_Registry",
    "Win32_Security_Cryptography",
    "Win32_Security_Authentication_Identity",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_ProcessStatus",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
    "Win32_System_WinRT",
    "Win32_UI_Accessibility",
    "Win32_UI_Shell",
    "Win32_System_DataExchange",
    "Win32_System_LibraryLoader",
    "Win32_System_StationsAndDesktops",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Security_Credentials_UI",
    "Security_Credentials",
] }

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "3"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3"
